version: "3"

volumes:
  yacut_static:
  yacut_postgres_data:

services:
  db:
    container_name: yacut-postgres
    image: postgres:13-alpine
    restart: always
    expose:
      - 5432
    volumes:
      - yacut_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../.env

  web:
    container_name: yacut-app
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    depends_on: [db]
    expose:
      - 5000
    volumes:
      - yacut_static:/app/yacut/static/
    env_file:
      - ../.env

  nginx:
    container_name: yacut-nginx
    image: nginx:stable
    restart: always
    depends_on: [web]
    expose:
      - 80
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - yacut_static:/var/www/static/
